// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVeIhT1THxvoxEBu_4AavSolyCir-hVfw',
    appId: '1:299482473495:web:d49d2f6cb8592c36f36852',
    messagingSenderId: '299482473495',
    projectId: 'coritario-cf487',
    authDomain: 'coritario-cf487.firebaseapp.com',
    storageBucket: 'coritario-cf487.firebasestorage.app',
    measurementId: 'G-SH5DYM43E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaOABGsihxd2gPacCszIUQwWVzfLhaa9E',
    appId: '1:299482473495:android:64e7fe5bd9ec4618f36852',
    messagingSenderId: '299482473495',
    projectId: 'coritario-cf487',
    storageBucket: 'coritario-cf487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrDUYCyFbOlftvX9m3vusBlrI2W2256nU',
    appId: '1:299482473495:ios:9b0853cf33962faff36852',
    messagingSenderId: '299482473495',
    projectId: 'coritario-cf487',
    storageBucket: 'coritario-cf487.firebasestorage.app',
    iosBundleId: 'com.example.coritarioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrDUYCyFbOlftvX9m3vusBlrI2W2256nU',
    appId: '1:299482473495:ios:9b0853cf33962faff36852',
    messagingSenderId: '299482473495',
    projectId: 'coritario-cf487',
    storageBucket: 'coritario-cf487.firebasestorage.app',
    iosBundleId: 'com.example.coritarioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVeIhT1THxvoxEBu_4AavSolyCir-hVfw',
    appId: '1:299482473495:web:30370271d7a8095cf36852',
    messagingSenderId: '299482473495',
    projectId: 'coritario-cf487',
    authDomain: 'coritario-cf487.firebaseapp.com',
    storageBucket: 'coritario-cf487.firebasestorage.app',
    measurementId: 'G-9YM4DE0QYK',
  );
}
